In [27]:
import torch
import numpy as np

In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.2556, 0.9232, 0.5474],
        [0.3436, 0.8056, 0.6878],
        [0.7029, 0.6197, 0.2786],
        [0.6344, 0.9877, 0.3958],
        [0.5211, 0.8306, 0.9721]])


# 指定数据类型dtype

In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


# new_*方法复制输入张量大小

In [6]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


# 重写数据类型rand_like(xx, dtype=)

In [7]:
x=torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[0.8924, 0.0779, 0.6445],
        [0.0917, 0.7362, 0.0086],
        [0.8568, 0.2320, 0.9652],
        [0.3311, 0.6548, 0.4004],
        [0.4387, 0.6138, 0.5182]])


# 获取张量大小size（）

In [8]:
x.size()%元祖

torch.Size([5, 3])

# 加法

In [9]:
y=torch.rand_like(x,dtype=torch.float)

In [12]:
print(y)
print(x+y)
result=torch.empty_like(x)#获得相同大小的tensor
print(torch.add(x,y,out=result))

tensor([[0.8176, 0.3016, 0.2462],
        [0.8851, 0.1103, 0.8344],
        [0.3991, 0.5946, 0.0187],
        [0.5006, 0.6179, 0.3799],
        [0.0472, 0.8356, 0.6692]])
tensor([[1.7100, 0.3794, 0.8907],
        [0.9768, 0.8465, 0.8430],
        [1.2559, 0.8266, 0.9839],
        [0.8317, 1.2727, 0.7802],
        [0.4860, 1.4494, 1.1874]])
tensor([[1.7100, 0.3794, 0.8907],
        [0.9768, 0.8465, 0.8430],
        [1.2559, 0.8266, 0.9839],
        [0.8317, 1.2727, 0.7802],
        [0.4860, 1.4494, 1.1874]])


#  修改tensor操作
##  1 任何改变tensor操作的方法名后都有下划线“_”,例如x.copy_（）
##  2 Numpy所有标准操作都可以使用

In [14]:
xx=x.copy_(y)%含义是把y复制到x身上

In [24]:
print(xx[1,:])
print(xx[:,1])
print(xx[3:,:])
print(xx[1:3,:])
print(xx[[1,3],:])

tensor([0.8851, 0.1103, 0.8344])
tensor([0.3016, 0.1103, 0.5946, 0.6179, 0.8356])
tensor([[0.5006, 0.6179, 0.3799],
        [0.0472, 0.8356, 0.6692]])
tensor([[0.8851, 0.1103, 0.8344],
        [0.3991, 0.5946, 0.0187]])
tensor([[0.8851, 0.1103, 0.8344],
        [0.5006, 0.6179, 0.3799]])


In [28]:
xx[xx>0.5]=np.nan

In [37]:
xx.where(xx>0.3,xx)

tensor([[   nan, 0.3016, 0.2462],
        [   nan, 0.1103,    nan],
        [0.3991,    nan, 0.0187],
        [   nan,    nan, 0.3799],
        [0.0472,    nan,    nan]])

# 重塑张量view()

In [45]:
x=torch.randn(4,4)
y=x.view(2,8)
z=x.view(-1,8) ##-1表示可以从其他维度推断
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([2, 8]) torch.Size([2, 8])


# 元素张量变成数 item()

In [48]:
a=torch.rand(1)
print(a)
a.item()

tensor([0.7207])


0.7206801772117615

# ndarray和tensor的相互转化

In [49]:
a=torch.ones(5)

In [50]:
a.numpy()

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [51]:
a=np.ones(5)

In [52]:
a=torch.Tensor(a)

In [53]:
a

tensor([1., 1., 1., 1., 1.])

In [54]:
x=torch.randn(3,requires_grad=True)
y=x*2
while y.data.norm()<1000:
    y=y*2
print(y)
    

tensor([-1160.9872,  -837.6100,     6.0198], grad_fn=<MulBackward>)


In [55]:
print(x)

tensor([-1.1338, -0.8180,  0.0059], requires_grad=True)
