# 网络的操作单元是张量，一个张量在网络中的运算因此需要跟踪操作

In [1]:
import torch

# 跟踪张量属性requires_grad=True

In [2]:
x=torch.ones(2,2,requires_grad=True)

In [3]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [5]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [6]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


# 梯度：
## 1）backward（）函数
## 2）x.grad

In [9]:
out.backward()##需要重要参数，grad_tensor,但是该例子输出是一个标量，因此可以省略。

In [10]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


# 理论解释:
# y相对x的梯度是一个雅克比矩阵
# torch.autograd本质上是一个向量—雅克比乘积计算引擎，V^T·J,恰当设置

# grad_tensor即V可以容易计算任意的求导组合

In [11]:
x=torch.randn(3,requires_grad=True)
y=x*2
while y.data.norm()<1000:
    y=y*2
print(y)
print(x)

tensor([  90.0783, -917.6239,  875.4804], grad_fn=<MulBackward>)
tensor([ 0.1759, -1.7922,  1.7099], requires_grad=True)


In [12]:
x=torch.randn(3,requires_grad=True)
y=x*2
print(y)
print(x)

tensor([ 0.0587, -1.6314,  2.8793], grad_fn=<MulBackward>)
tensor([ 0.0293, -0.8157,  1.4397], requires_grad=True)


# 通过设置v计算output为向量的雅克比矩阵

In [15]:
v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([0.2000, 2.0000, 0.0002])


In [16]:
v=torch.tensor([0.5,6.0,0.0051],dtype=torch.float)
y.backward(v)
print(x.grad)#设置不同的向量得到的结果不同

tensor([ 1.2000, 14.0000,  0.0104])


# with torch.no_grad():   取消对张量的所有跟踪操作

In [17]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
